apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapps-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: boardgame-deployment
    count: 1

configMapGenerator:
  - name: boardgame-config
    behavior: merge
    literals:
      - spring.profiles.active=dev
      - logging.level.root=DEBUG
      - logging.level.com.javaproject=DEBUG

patchesStrategicMerge:
  - deployment-patch.yaml
