apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapps-staging

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: boardgame-deployment
    count: 2

configMapGenerator:
  - name: boardgame-config
    behavior: merge
    literals:
      - spring.profiles.active=staging
      - logging.level.root=INFO

patchesStrategicMerge:
  - deployment-patch.yaml
